const KEY = "dailyhorse.browser-library.v1";
const state = { tabs: [], query: "", library: { folders: [], pages: [], preferences: { collapsed: false, folders: {} } } };
const $ = (id) => document.getElementById(id);
const normalize = (value) => { const url = new URL(value); if (!/^https?:$/.test(url.protocol)) throw new Error("Nur http(s)-Seiten können gespeichert werden."); url.hash = ""; return url.toString(); };
const domain = (url) => { try { return new URL(url).hostname.replace(/^www\./, ""); } catch { return "Lokale Seite"; } };
const escape = (value) => String(value || "").slice(0, 240);
const persist = () => chrome.storage.local.set({ [KEY]: state.library });
async function load() { const data = await chrome.storage.local.get(KEY); if (data[KEY]) state.library = { ...state.library, ...data[KEY], preferences: { collapsed: false, folders: {}, ...data[KEY].preferences } }; $("sidebar").classList.toggle("collapsed", state.library.preferences.collapsed); }
async function refreshTabs() { state.tabs = (await chrome.tabs.query({ currentWindow: true })).filter((tab) => tab.url && /^(https?|file):/i.test(tab.url)); render(); }
function icon(img, tab) { const fallback = `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><rect width="16" height="16" rx="4" fill="#472968"/><text x="8" y="11" text-anchor="middle" fill="#ddc7ff" font-size="9">${escape((tab.title || domain(tab.url))[0] || "•")}</text></svg>`)}`; img.src = tab.favIconUrl || fallback; img.onerror = () => { img.onerror = null; img.src = fallback; }; }
function matches(...values) { const query = state.query.trim().toLowerCase(); return !query || values.join(" ").toLowerCase().includes(query); }
function item(record, type, active = false) { const node = $("itemTemplate").content.firstElementChild.cloneNode(true); node.classList.toggle("is-active", active); node.draggable = type === "page"; const main = node.querySelector(".item-main"); const img = node.querySelector("img"); const [title, sub] = type === "tab" ? [record.title || domain(record.url), domain(record.url)] : [record.title, domain(record.url)]; icon(img, record); img.alt = ""; node.querySelector("b").textContent = title; node.querySelector("small").textContent = `${type === "tab" && record.pinned ? "Angeheftet · " : ""}${sub}`; main.addEventListener("click", () => type === "tab" ? chrome.tabs.update(record.id, { active: true }).then(() => chrome.windows.update(record.windowId, { focused: true })) : openSaved(record)); const more = node.querySelector(".more"); more.title = "Weitere Aktionen"; more.addEventListener("click", () => actions(record, type)); if (type === "page") { node.addEventListener("dragstart", (event) => event.dataTransfer.setData("text/plain", record.id)); } return node; }
function render() { const open = $("openTabs"); open.replaceChildren(); const visibleTabs = state.tabs.filter((tab) => matches(tab.title, tab.url)); visibleTabs.forEach((tab) => open.append(item(tab, "tab", tab.active))); $("tabCount").textContent = String(visibleTabs.length); const folders = $("folders"); folders.replaceChildren(); const visiblePages = state.library.pages.filter((page) => matches(page.title, page.url, state.library.folders.find((folder) => folder.id === page.folderId)?.name)); const unfiled = visiblePages.filter((page) => !page.folderId); if (unfiled.length) folders.append(folderNode({ id: "", name: "Ohne Ordner" }, unfiled, true)); state.library.folders.sort((a, b) => a.order - b.order).forEach((folder) => folders.append(folderNode(folder, visiblePages.filter((page) => page.folderId === folder.id)))); $("pageCount").textContent = String(state.library.pages.length); $("emptySaved").hidden = Boolean(state.library.pages.length); }
function folderNode(folder, pages, fixed = false) { const wrap = document.createElement("section"); wrap.className = "folder"; const head = document.createElement("div"); head.className = "folder-head"; const toggle = document.createElement("button"); toggle.className = "folder-toggle"; const open = state.library.preferences.folders[folder.id] !== false; toggle.textContent = `${open ? "▾" : "▸"} ${folder.name} ${pages.length ? `(${pages.length})` : ""}`; const body = document.createElement("div"); body.className = "folder-pages"; body.hidden = !open; pages.sort((a, b) => a.order - b.order).forEach((page) => body.append(item(page, "page"))); toggle.addEventListener("click", () => { state.library.preferences.folders[folder.id] = !open; persist(); render(); }); head.append(toggle); if (!fixed) { const actions = document.createElement("span"); actions.className = "folder-actions"; const rename = document.createElement("button"); rename.textContent = "✎"; rename.title = "Ordner umbenennen"; rename.onclick = () => renameFolder(folder); const remove = document.createElement("button"); remove.textContent = "×"; remove.title = "Ordner löschen"; remove.onclick = () => deleteFolder(folder); actions.append(rename, remove); head.append(actions); } wrap.append(head, body); if (!fixed) { wrap.addEventListener("dragover", (event) => { event.preventDefault(); wrap.classList.add("drop-target"); }); wrap.addEventListener("dragleave", () => wrap.classList.remove("drop-target")); wrap.addEventListener("drop", (event) => { event.preventDefault(); wrap.classList.remove("drop-target"); movePage(event.dataTransfer.getData("text/plain"), folder.id); }); } return wrap; }
async function openSaved(page) { const match = state.tabs.find((tab) => normalize(tab.url) === page.url); if (match) { await chrome.tabs.update(match.id, { active: true }); await chrome.windows.update(match.windowId, { focused: true }); } else await chrome.tabs.create({ url: page.url, active: true }); }
function save(tab, folderId = null) { try { const url = normalize(tab.url); const existing = state.library.pages.find((page) => page.url === url); if (existing) { existing.folderId = folderId ?? existing.folderId; existing.updatedAt = Date.now(); } else state.library.pages.push({ id: crypto.randomUUID(), title: escape(tab.title || domain(url)), url, favicon: tab.favIconUrl || "", folderId, order: Date.now(), createdAt: Date.now(), updatedAt: Date.now() }); persist(); render(); } catch (error) { alert(error.message); } }
function chooseFolder(page) { const choices = state.library.folders.map((folder, index) => `${index + 1}. ${folder.name}`).join("\n"); const answer = prompt(`Zielordner wählen (Nummer, leer = ohne Ordner):\n${choices}`, ""); if (answer === null) return; const folder = state.library.folders[Number(answer) - 1]; movePage(page.id, folder?.id || null); }
function movePage(id, folderId) { const page = state.library.pages.find((item) => item.id === id); if (!page) return; page.folderId = folderId || null; page.order = Date.now(); page.updatedAt = Date.now(); persist(); render(); }
function actions(record, type) { const choices = type === "tab" ? "1. Speichern\n2. Anheften/loslösen\n3. Neu laden\n4. Schließen" : "1. Öffnen\n2. Verschieben\n3. Umbenennen\n4. Entfernen"; const answer = prompt(choices, ""); if (type === "tab") { if (answer === "1") save(record); if (answer === "2") chrome.tabs.update(record.id, { pinned: !record.pinned }); if (answer === "3") chrome.tabs.reload(record.id); if (answer === "4") chrome.tabs.remove(record.id); } else { if (answer === "1") openSaved(record); if (answer === "2") chooseFolder(record); if (answer === "3") { const title = prompt("Seitentitel", record.title); if (title?.trim()) { record.title = escape(title.trim()); record.updatedAt = Date.now(); persist(); render(); } } if (answer === "4" && confirm(`„${record.title}“ entfernen?`)) { state.library.pages = state.library.pages.filter((page) => page.id !== record.id); persist(); render(); } } }
function newFolder() { const name = prompt("Ordnername"); if (!name?.trim()) return; state.library.folders.push({ id: crypto.randomUUID(), name: escape(name.trim()), order: Date.now(), createdAt: Date.now(), updatedAt: Date.now() }); persist(); render(); }
function renameFolder(folder) { const name = prompt("Ordnername", folder.name); if (!name?.trim()) return; folder.name = escape(name.trim()); folder.updatedAt = Date.now(); persist(); render(); }
function deleteFolder(folder) { const count = state.library.pages.filter((page) => page.folderId === folder.id).length; if (!confirm(count ? `Ordner löschen? ${count} Seite(n) bleiben ohne Ordner erhalten.` : "Ordner löschen?")) return; state.library.pages.forEach((page) => { if (page.folderId === folder.id) page.folderId = null; }); state.library.folders = state.library.folders.filter((item) => item.id !== folder.id); delete state.library.preferences.folders[folder.id]; persist(); render(); }
$("search").addEventListener("input", (event) => { state.query = event.target.value; render(); }); $("refreshTabs").onclick = refreshTabs; $("saveActive").onclick = async () => { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (tab) save(tab); }; $("newFolder").onclick = newFolder; $("toggle").onclick = () => { state.library.preferences.collapsed = !state.library.preferences.collapsed; persist(); $("sidebar").classList.toggle("collapsed", state.library.preferences.collapsed); }; [chrome.tabs.onCreated, chrome.tabs.onUpdated, chrome.tabs.onRemoved, chrome.tabs.onActivated, chrome.tabs.onMoved].forEach((event) => event.addListener(() => refreshTabs())); await load(); await refreshTabs();
