import { useEffect, useState } from "react";
import { BarChart3, BookOpen, ExternalLink, RefreshCw, Rss, Search, Settings2, X } from "lucide-react";
import { api, type Editorial, type Kpi, type Source } from "./api";
import "./workspace.css";
import { AgentWorkspace } from "./components/AgentWorkspace";
import { WorkOsHome } from "./components/WorkOsHome";

const labels: Record<string, string> = { users: "Aktive Nutzer", sessions: "Sitzungen", pageviews: "Seitenaufrufe", youtube_views: "YouTube Views", instagram_reach: "Instagram Reichweite", search_clicks: "Google Klicks", play_downloads: "Play Installationen", github_views: "GitHub Views" };
const time = (value: string | null) => value ? new Date(value).toLocaleString("de-DE") : "noch nie";
export default function App() {
  const [view, setView] = useState<"today" | "kpis" | "sources" | "editor" | "agent">("today"); const [kpis, setKpis] = useState<Kpi[]>([]); const [sources, setSources] = useState<Source[]>([]); const [editorial, setEditorial] = useState<Editorial | null>(null); const [busy, setBusy] = useState(false); const [palette, setPalette] = useState(false);
  const load = async () => { const [overview, sourceData, editorialData] = await Promise.all([api.overview(), api.sources(), api.editorial()]); setKpis(overview.kpis); setSources(sourceData); setEditorial(editorialData); };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPalette((open) => !open); } if (event.key === "Escape") setPalette(false); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  const refresh = async () => { setBusy(true); try { await api.sync(); await load(); } finally { setBusy(false); } };
  const metrics = (items: Kpi[]) => <section className="metrics">{items.map((item) => <article key={item.id}><span>{labels[item.id] ?? item.id}</span><strong>{item.value === null ? "—" : new Intl.NumberFormat("de-DE").format(item.value)}</strong><small>{item.value === null ? (item.info.availability === "available" ? "Verbunden, noch keine Messwerte" : "Nicht verbunden") : `Direkt gemessen · ${item.info.source}`}</small></article>)}</section>;
  const navigate = (next: typeof view) => { setView(next); setPalette(false); };
  return <main className="workhorse"><header className="hero"><img src="/api/assets/header" alt="Haas Arts"/><div><p>DAILY WORKHORSE</p><h1>Heute klar. Morgen vorbereitet.</h1></div><button className="palette-trigger" onClick={() => setPalette(true)}><Search size={16}/> Suche <kbd>Ctrl K</kbd></button></header><nav className="workspace-nav"><button className={view === "today" ? "active" : ""} onClick={() => navigate("today")}>Heute</button><button className={view === "kpis" ? "active" : ""} onClick={() => navigate("kpis")}>KPI-Dashboard</button><button className={view === "sources" ? "active" : ""} onClick={() => navigate("sources")}>Datenquellen</button><button className={view === "editor" ? "active" : ""} onClick={() => navigate("editor")}>Redaktionsmaske</button><button className={view === "agent" ? "active" : ""} onClick={() => navigate("agent")}>OpenCode</button></nav>{palette && <div className="palette-backdrop" onMouseDown={() => setPalette(false)}><section className="palette" onMouseDown={(event) => event.stopPropagation()}><header><b>Command Palette</b><button onClick={() => setPalette(false)}><X size={16}/></button></header>{([ ["today", "Heute öffnen"], ["agent", "OpenCode Command Center"], ["kpis", "KPI-Dashboard öffnen"], ["sources", "Datenquellen prüfen"], ["editor", "Redaktionsmaske öffnen"] ] as Array<[typeof view, string]>).map(([target, label]) => <button key={target} onClick={() => navigate(target)}>{label}</button>)}</section></div>}{view === "agent" ? <AgentWorkspace/> : view === "editor" ? <section className="editor"><a href="http://127.0.0.1:8081/" target="_blank" rel="noreferrer">Redaktionsmaske separat öffnen</a><iframe title="Haas Arts Redaktionsmaske" src="http://127.0.0.1:8081/"/></section> : view === "kpis" ? metrics(kpis) : view === "sources" ? <section className="sources">{sources.map((source) => <article className="source-card" key={source.id}><b>{source.name}</b><span>{source.status_detail}</span><small>Letzter Erfolg: {time(source.last_success_at)}</small></article>)}</section> : view === "today" ? <WorkOsHome onOpenAgent={() => navigate("agent")}/> : <>
    <section className="command"><img src="/api/assets/logo" alt="HA"/><div><b>Tagesstart</b><span>Prüfe Quellen, priorisiere Themen, publiziere bewusst.</span></div><button onClick={() => void refresh()} disabled={busy}><RefreshCw size={16} className={busy ? "spin" : ""}/>{busy ? "Aktualisiere" : "Aktualisieren"}</button><a href={editorial?.adminUrl ?? "http://127.0.0.1:8081/"} target="_blank" rel="noreferrer"><Settings2 size={16}/> Redaktion öffnen</a><a href={editorial?.blogUrl ?? "https://www.haasarts.de/blog/"} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Blog ansehen</a></section>
    {metrics(kpis.filter((item) => ["users", "sessions", "search_clicks", "youtube_views", "github_views"].includes(item.id)))}
    <section className="grid"><article className="panel editorial"><div className="panel-head"><div><p>REDAKTION</p><h2>Publikationslage</h2></div><BookOpen size={21}/></div><div className="totals"><div><strong>{editorial?.publishedCount ?? 0}</strong><span>veröffentlicht</span></div><div><strong>{editorial?.draftCount ?? 0}</strong><span>Entwürfe</span></div><div><strong>{editorial?.suggestions.length ?? 0}</strong><span>Vorschläge</span></div></div><p className="note">Artikelstand: {time(editorial?.generatedAt ?? null)} · News-Scan: {time(editorial?.newsUpdatedAt ?? null)}</p><h3>Als Nächstes prüfen</h3>{editorial?.suggestions.slice(0, 4).map((item) => <a className="suggestion" key={item.id} href={item.sourceItemUrl} target="_blank" rel="noreferrer"><span>{item.source}</span><b>{item.title}</b><em>{item.score ?? 0}</em></a>)}</article>
      <article className="panel"><div className="panel-head"><div><p>QUELLEN</p><h2>Wahrheitsstatus</h2></div><Rss size={21}/></div>{sources.map((source) => <div className="source" key={source.id}><i className={source.status}/><div><b>{source.name}</b><span>{source.status_detail}</span></div><small>{time(source.last_success_at)}</small></div>)}<div className="health"><b>Redaktionsquellen</b><span>{editorial?.sourceHealth.green ?? 0} Feed/GitHub · {editorial?.sourceHealth.yellow ?? 0} manuell prüfen · {editorial?.sourceHealth.grey ?? 0} deaktiviert</span></div></article></section>
    <section className="panel latest"><div className="panel-head"><div><p>VERÖFFENTLICHT</p><h2>Letzte Artikel</h2></div><BarChart3 size={21}/></div>{editorial?.latest.map((article) => <a key={article.url} href={article.url} target="_blank" rel="noreferrer"><span>{article.date} · {article.category}</span><b>{article.title}</b><small>{article.readingTime ?? "—"} Min.</small></a>)}</section></>}
  </main>;
}
