import { useEffect, useRef, useState } from "react";
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import "@xterm/xterm/css/xterm.css";

type Status = { sessionId: string; cwd: string; repository: string | null; branch: string | null; agent: string; terminal: string; task: string | null; error: string | null };
type Center = { sessions: Array<{ id: string; name: string; cwd: string; status: string; task_id: string | null }>; tasks: Array<{ id: string; title: string; status: string; priority: number; session_id: string | null }>; events: Array<{ id: number; kind: string; detail: string | null; created_at: string }> };
const base = () => location.protocol === "https:" ? "wss" : "ws";
function Pty({ target, token }: { target: "agent" | "terminal"; token: string }) {
  const host = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!host.current) return; const term = new Terminal({ cursorBlink: true, scrollback: 4000, theme: { background: "#160923", foreground: "#f6f0ff", cursor: "#cbb8ef" } }); const fit = new FitAddon(); term.loadAddon(fit); term.open(host.current); fit.fit(); const socket = new WebSocket(`${base()}://${location.host}/api/workspace/socket?target=${target}`, ["daily-horse-v1", token]); socket.onmessage = (event) => { const message = JSON.parse(event.data) as { type: string; data?: string }; if (message.type === "output") term.write(message.data ?? ""); }; term.onData((data) => socket.readyState === WebSocket.OPEN && socket.send(JSON.stringify({ type: "input", data }))); const resize = () => { fit.fit(); socket.readyState === WebSocket.OPEN && socket.send(JSON.stringify({ type: "resize", cols: term.cols, rows: term.rows })); }; const observer = new ResizeObserver(resize); observer.observe(host.current); socket.onopen = resize; return () => { observer.disconnect(); socket.close(); term.dispose(); }; }, [target, token]);
  return <div className="pty" ref={host}/>;
}
export function AgentWorkspace() {
  const [token, setToken] = useState<string>(); const [status, setStatus] = useState<Status>(); const [center, setCenter] = useState<Center>(); const [task, setTask] = useState(""); const [error, setError] = useState<string>();
  const bootstrap = async () => { try { const response = await fetch("/api/workspace/bootstrap"); const body = await response.json() as { token?: string; status?: Status; error?: string }; if (!response.ok || !body.token || !body.status) throw new Error(body.error ?? "Companion is unavailable."); setToken(body.token); setStatus(body.status); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Companion is unavailable."); } };
  useEffect(() => { void bootstrap(); }, []);
  useEffect(() => { if (!token) return; const load = () => fetch("/api/workspace/command-center", { headers: { "x-daily-horse-token": token } }).then((response) => response.ok ? response.json() as Promise<Center> : Promise.reject()).then(setCenter).catch(() => setError("Command Center konnte nicht synchronisieren.")); void load(); const timer = window.setInterval(load, 3000); return () => window.clearInterval(timer); }, [token]);
  const control = async (action: "start" | "restart" | "new" | "stop", target: "agent" | "terminal") => { if (!token) return; const response = await fetch("/api/workspace/control", { method: "POST", headers: { "Content-Type": "application/json", "x-daily-horse-token": token }, body: JSON.stringify({ action, target }) }); setStatus(await response.json() as Status); };
  const send = async () => { if (!task.trim() || !token) return; const response = await fetch("/api/workspace/task", { method: "POST", headers: { "Content-Type": "application/json", "x-daily-horse-token": token }, body: JSON.stringify({ message: task }) }); const body = await response.json() as Status & { error?: string }; if (!response.ok) setError(body.error ?? "Task was rejected."); else { setStatus(body); setTask(""); } };
  return <section className="agent-workspace"><header><div><p>OPENCODE WORKSPACE</p><h2>Command Center</h2></div><div className="workspace-controls"><button onClick={() => void control("restart", "agent")}>Restart</button><button onClick={() => void control("new", "agent")}>New session</button><button onClick={() => void control("stop", "agent")}>Stop</button></div></header><div className="agent-context"><span>Agenten {center?.sessions.length ?? 0}</span><span>Aktiv {center?.tasks.filter((item) => item.status === "running").length ?? 0}</span><span>Queue {center?.tasks.filter((item) => item.status === "queued").length ?? 0}</span><span>CWD {status?.cwd ?? "—"}</span></div><div className="quick-task"><input value={task} onChange={(event) => setTask(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="OpenCode, erledige …"/><button onClick={() => void send()}>In Queue</button></div>{error && <p className="workspace-error">{error} <button onClick={() => void bootstrap()}>Neu verbinden</button></p>}<div className="command-grid"><article><h3>Agents</h3>{center?.sessions.map((item) => <p key={item.id}><b>{item.name}</b> · {item.status}<small>{item.cwd}</small></p>)}</article><article><h3>Active Jobs & Queue</h3>{center?.tasks.slice(0, 8).map((item) => <p key={item.id}><b>{item.title}</b> · {item.status}<small>Priorität {item.priority}</small></p>)}</article><article><h3>Recent Activity</h3>{center?.events.slice(0, 8).map((item) => <p key={item.id}>{item.kind}<small>{new Date(item.created_at).toLocaleTimeString("de-DE")}</small></p>)}</article></div><div className="pty-grid"><article><h3>OpenCode</h3>{token && <Pty target="agent" token={token}/>}</article><article><div className="terminal-head"><h3>Terminal</h3><span><button onClick={() => void control("restart", "terminal")}>Neu starten</button><button onClick={() => void control("stop", "terminal")}>Schließen</button></span></div>{token && <Pty target="terminal" token={token}/>}</article></div></section>;
}
