import { useEffect, useRef, useState } from "react";
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import "@xterm/xterm/css/xterm.css";

type Status = { sessionId: string; cwd: string; repository: string | null; branch: string | null; agent: string; terminal: string; task: string | null; error: string | null };
const base = () => location.protocol === "https:" ? "wss" : "ws";
function Pty({ target, token }: { target: "agent" | "terminal"; token: string }) {
  const host = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!host.current) return; const term = new Terminal({ cursorBlink: true, scrollback: 4000, theme: { background: "#160923", foreground: "#f6f0ff", cursor: "#cbb8ef" } }); const fit = new FitAddon(); term.loadAddon(fit); term.open(host.current); fit.fit(); const socket = new WebSocket(`${base()}://${location.host}/api/workspace/socket?target=${target}`, ["daily-horse-v1", token]); socket.onmessage = (event) => { const message = JSON.parse(event.data) as { type: string; data?: string }; if (message.type === "output") term.write(message.data ?? ""); }; term.onData((data) => socket.readyState === WebSocket.OPEN && socket.send(JSON.stringify({ type: "input", data }))); const resize = () => { fit.fit(); socket.readyState === WebSocket.OPEN && socket.send(JSON.stringify({ type: "resize", cols: term.cols, rows: term.rows })); }; const observer = new ResizeObserver(resize); observer.observe(host.current); socket.onopen = resize; return () => { observer.disconnect(); socket.close(); term.dispose(); }; }, [target, token]);
  return <div className="pty" ref={host}/>;
}
export function AgentWorkspace() {
  const [token, setToken] = useState<string>(); const [status, setStatus] = useState<Status>(); const [task, setTask] = useState(""); const [error, setError] = useState<string>();
  const bootstrap = async () => { try { const response = await fetch("/api/workspace/bootstrap"); const body = await response.json() as { token?: string; status?: Status; error?: string }; if (!response.ok || !body.token || !body.status) throw new Error(body.error ?? "Companion is unavailable."); setToken(body.token); setStatus(body.status); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Companion is unavailable."); } };
  useEffect(() => { void bootstrap(); }, []);
  const control = async (action: "start" | "restart" | "new" | "stop", target: "agent" | "terminal") => { if (!token) return; const response = await fetch("/api/workspace/control", { method: "POST", headers: { "Content-Type": "application/json", "x-daily-horse-token": token }, body: JSON.stringify({ action, target }) }); setStatus(await response.json() as Status); };
  const send = async () => { if (!task.trim() || !token) return; const response = await fetch("/api/workspace/task", { method: "POST", headers: { "Content-Type": "application/json", "x-daily-horse-token": token }, body: JSON.stringify({ message: task }) }); const body = await response.json() as Status & { error?: string }; if (!response.ok) setError(body.error ?? "Task was rejected."); else { setStatus(body); setTask(""); } };
  return <section className="agent-workspace"><header><div><p>OPENCODE WORKSPACE</p><h2>Agent und Terminal</h2></div><div className="workspace-controls"><button onClick={() => void control("restart", "agent")}>Restart</button><button onClick={() => void control("new", "agent")}>New session</button><button onClick={() => void control("stop", "agent")}>Stop</button></div></header><div className="agent-context"><span>Session {status?.sessionId ?? "verbinde..."}</span><span>CWD {status?.cwd ?? "—"}</span><span>Repository {status?.repository ?? "kein Repository"}</span><span>Agent {status?.agent ?? "unbekannt"}</span>{status?.task && <span>Aufgabe {status.task}</span>}</div><div className="quick-task"><input value={task} onChange={(event) => setTask(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="OpenCode, erledige …"/><button onClick={() => void send()}>Senden</button></div>{error && <p className="workspace-error">{error} <button onClick={() => void bootstrap()}>Neu verbinden</button></p>}<div className="pty-grid"><article><h3>OpenCode</h3>{token && <Pty target="agent" token={token}/>}</article><article><div className="terminal-head"><h3>Terminal</h3><button onClick={() => void control("restart", "terminal")}>Neu starten</button></div>{token && <Pty target="terminal" token={token}/>}</article></div></section>;
}
