import { useEffect, useRef, useState } from "react";

type Device = { id: string; name: string; paired: boolean; reachable: boolean; batteryLevel: number | null };
type DeviceResult = { status: "available" | "unavailable"; devices: Device[]; error?: string };

export function DeviceBridge({ token, onError }: { token: string; onError: (error: string) => void }) {
  const [result, setResult] = useState<DeviceResult>(); const [notice, setNotice] = useState<string>(); const [url, setUrl] = useState(""); const files = useRef<Record<string, HTMLInputElement | null>>({});
  const headers = { "x-daily-horse-token": token };
  const load = async () => { const response = await fetch("/api/devices", { headers }); const body = await response.json() as DeviceResult; if (!response.ok) throw new Error(body.error ?? "Geräte konnten nicht geladen werden."); setResult(body); };
  const submit = (action: () => Promise<void>) => void action().catch((error) => onError(error instanceof Error ? error.message : "Geräteaktion fehlgeschlagen."));
  const send = async (id: string, action: string, body?: object) => { const response = await fetch(`/api/devices/${encodeURIComponent(id)}/${action}`, { method: "POST", headers: { ...headers, "Content-Type": "application/json" }, body: JSON.stringify(body ?? {}) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Geräteaktion fehlgeschlagen."); };
  useEffect(() => { void load().catch((error) => onError(error instanceof Error ? error.message : "Geräte konnten nicht geladen werden.")); }, [token]);
  useEffect(() => { const listener = (event: Event) => { const detail = (event as CustomEvent<{ action: "clipboard" | "ring" | "file"; id: string }>).detail; const device = result?.devices.find((item) => item.id === detail?.id); if (!device) return; if (detail.action === "clipboard") clipboard(device); if (detail.action === "ring") submit(async () => { await send(device.id, "ring"); setNotice(`${device.name} wird über KDE Connect angerufen.`); }); if (detail.action === "file") files.current[device.id]?.click(); }; window.addEventListener("dailyhorse:device-action", listener); return () => window.removeEventListener("dailyhorse:device-action", listener); }, [result]);
  const clipboard = (device: Device) => submit(async () => { if (!navigator.clipboard?.readText) throw new Error("Der Browser erlaubt keinen Zugriff auf die Zwischenablage."); await send(device.id, "send-clipboard", { text: await navigator.clipboard.readText() }); setNotice(`Zwischenablage an ${device.name} übergeben.`); });
  const file = (device: Device, selected?: File) => submit(async () => { if (!selected) return; const response = await fetch(`/api/devices/${encodeURIComponent(device.id)}/send-file`, { method: "POST", headers: { ...headers, "Content-Type": "application/octet-stream", "x-dailyhorse-filename": selected.name }, body: selected }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Datei konnte nicht übergeben werden."); setNotice(`Datei an ${device.name} übergeben.`); });
  if (!result) return <article className="work-card devices"><div className="work-card-head"><h3>Geräte</h3><button onClick={() => submit(load)}>Aktualisieren</button></div><p className="empty">KDE Connect wird geprüft.</p></article>;
  if (result.status === "unavailable") return <article className="work-card devices"><div className="work-card-head"><h3>Geräte</h3><span>Nicht verfügbar</span></div><p className="empty">KDE Connect ist auf diesem System nicht verfügbar.</p></article>;
  return <article className="work-card devices"><div className="work-card-head"><h3>Geräte</h3><button onClick={() => submit(load)}>Aktualisieren</button></div>{notice && <p className="device-notice" role="status">{notice}</p>}{result.devices.length ? result.devices.map((device) => <section className="device-row" key={device.id}><div><b><span aria-hidden="true" className={device.reachable ? "device-dot online" : "device-dot"}/> {device.name}</b><small>{device.batteryLevel === null ? "" : `${device.batteryLevel} % · `}{device.reachable ? "Verbunden" : device.paired ? "Offline" : "Nicht gekoppelt"}</small></div>{device.reachable && <><div className="device-actions"><input ref={(node) => { files.current[device.id] = node; }} type="file" tabIndex={-1} aria-label={`Datei an ${device.name} senden`} onChange={(event) => file(device, event.target.files?.[0])}/><button onClick={() => files.current[device.id]?.click()}>Datei senden</button><button onClick={() => clipboard(device)}>Zwischenablage senden</button><button onClick={() => submit(async () => { await send(device.id, "ring"); setNotice(`${device.name} wird über KDE Connect angerufen.`); })}>Klingeln</button></div><form className="device-url" onSubmit={(event) => { event.preventDefault(); submit(async () => { await send(device.id, "send-url", { url }); setNotice(`Link an ${device.name} übergeben.`); setUrl(""); }); }}><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https:// Link senden" aria-label={`Link an ${device.name} senden`}/><button disabled={!url.trim()}>Link senden</button></form></>}</section>) : <p className="empty">Noch kein KDE-Connect-Gerät gekoppelt. Pairing und Vertrauen werden in KDE Connect verwaltet.</p>}</article>;
}
