import { useEffect, useState } from "react";

type Root = { id: string; name: string; path: string };
type Entry = { name: string; path: string; directory: boolean; size: number | null };
const displaySize = (size: number | null) => size === null ? "Ordner" : `${Math.ceil(size / 1024)} KB`;

export function LocalFilesWorkspace() {
  const [token, setToken] = useState(""); const [roots, setRoots] = useState<Root[]>([]); const [rootId, setRootId] = useState(""); const [current, setCurrent] = useState(""); const [entries, setEntries] = useState<Entry[]>([]); const [selected, setSelected] = useState<Entry>(); const [error, setError] = useState(""); const [adding, setAdding] = useState(false); const [name, setName] = useState(""); const [rootPath, setRootPath] = useState("");
  const api = async <T,>(url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, headers: { "x-daily-horse-token": token, "Content-Type": "application/json", ...init?.headers } }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Lokale Dateioperation fehlgeschlagen."); return body; };
  const refresh = async (id = rootId, folder = current) => { if (!id) return setEntries([]); const result = await api<{ entries: Entry[] }>(`/api/local-files/${id}?path=${encodeURIComponent(folder)}`); setEntries(result.entries); setSelected(undefined); };
  useEffect(() => { void (async () => { try { const session = await (await fetch("/api/workspace/bootstrap")).json() as { token?: string }; if (!session.token) throw new Error("Lokale Workspace-Sitzung erforderlich."); setToken(session.token); const response = await fetch("/api/local-files/roots", { headers: { "x-daily-horse-token": session.token } }); const data = await response.json() as { roots: Root[] }; setRoots(data.roots); setRootId(data.roots[0]?.id ?? ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Lokale Dateien sind nicht verfügbar."); } })(); }, []);
  useEffect(() => { if (token && rootId) void refresh().catch((reason) => setError(reason.message)); }, [token, rootId]);
  const run = async (operation: "mkdir" | "rename" | "copy" | "move" | "open") => { const target = operation === "mkdir" ? prompt("Name des neuen Ordners") : operation === "rename" ? prompt("Neuer Name", selected?.name) : operation === "copy" || operation === "move" ? prompt("Zielpfad im aktuellen Root", selected?.name) : selected?.path; if (!target) return; try { const url = operation === "copy" || operation === "move" ? `/api/local-files/${operation}` : `/api/local-files/${rootId}/${operation}`; const body = operation === "mkdir" ? { path: current ? `${current}/${target}` : target } : operation === "rename" ? { source: selected?.path, destination: current ? `${current}/${target}` : target } : operation === "copy" || operation === "move" ? { sourceRootId: rootId, source: selected?.path, destinationRootId: rootId, destination: target } : { path: target }; await api(url, { method: "POST", body: JSON.stringify(body) }); if (operation !== "open") await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Dateioperation fehlgeschlagen."); } };
  const createRoot = async (event: React.FormEvent) => { event.preventDefault(); try { const data = await api<{ root: Root }>("/api/local-files/roots", { method: "POST", body: JSON.stringify({ name, path: rootPath }) }); setRoots((value) => [...value, data.root]); setRootId(data.root.id); setCurrent(""); setAdding(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Root konnte nicht freigegeben werden."); } };
  const root = roots.find((item) => item.id === rootId);
  return <section className="file-workspace local-file-workspace"><header className="today-head"><div><p>LOCAL EXPLORER</p><h2>Lokale Dateien</h2><span>Nur ausdrücklich freigegebene Ordner. Löschen ist nicht verfügbar.</span></div><div className="file-toolbar"><button onClick={() => setAdding(true)}>Ordner freigeben</button></div></header>{error && <p className="work-os-error">{error}</p>}{adding && <form className="file-setup" onSubmit={createRoot}><b>Vertrauenswürdigen Ordner hinzufügen</b><input required placeholder="Name" value={name} onChange={(event) => setName(event.target.value)}/><input required placeholder="Absoluter vorhandener Ordnerpfad" value={rootPath} onChange={(event) => setRootPath(event.target.value)}/><button>Freigeben</button><button type="button" onClick={() => setAdding(false)}>Abbrechen</button></form>}<div className="local-file-layout"><aside className="local-roots"><p>QUICK ACCESS</p>{roots.length ? roots.map((item) => <button key={item.id} className={item.id === rootId ? "selected" : ""} title={item.path} onClick={() => { setRootId(item.id); setCurrent(""); }}>{item.name}<small>{item.path}</small></button>) : <span>Noch kein Ordner freigegeben.</span>}</aside><article className="file-panel"><header><div><p>ORDNER</p><b>{root ? `${root.path}${current ? `/${current}` : ""}` : "Ordner auswählen"}</b></div><div className="file-actions"><button disabled={!current} onClick={() => { const next = current.split("/").slice(0, -1).join("/"); setCurrent(next); void refresh(rootId, next); }}>Hoch</button><button disabled={!rootId} onClick={() => void run("mkdir")}>Neuer Ordner</button></div></header><div className="file-list" role="list" aria-label="Lokale Dateien">{entries.map((item) => <button key={item.path} role="listitem" className={selected?.path === item.path ? "selected" : ""} onClick={() => setSelected(item)} onDoubleClick={() => { if (item.directory) { setCurrent(item.path); void refresh(rootId, item.path); } else void run("open"); }}><span>{item.directory ? "Ordner" : "Datei"}</span><b>{item.name}</b><small>{displaySize(item.size)}</small></button>)}</div><footer><div className="file-actions"><button disabled={!selected} onClick={() => void run("open")}>Öffnen</button><button disabled={!selected} onClick={() => void run("rename")}>Umbenennen</button><button disabled={!selected} onClick={() => void run("copy")}>Kopieren</button><button disabled={!selected} onClick={() => void run("move")}>Verschieben</button></div></footer></article></div></section>;
}
