import { useEffect, useState } from "react";
import "./today-integrations.css";
import { DeviceBridge } from "./DeviceBridge";

type Project = { id: string; name: string; description: string | null; status: string; task_count: number; open_task_count: number };
type Task = { id: string; title: string; status: string; priority: number; project_id: string | null };
type Research = { id: string; title: string; notes: string | null; url: string | null; status: string; project_id: string | null; project_name: string | null };
type Attention = { type: "task" | "event" | "setup"; id: string; label: string; status: string; detail: string | null };
type WorkOs = { projects: Project[]; tasks: Task[]; research: Research[]; attention: Attention[]; setups: Array<{ provider: string; state: string; detail: string }> };
type MailMessage = { uid: number; subject: string; from: string[]; date: string | null; unread: boolean; flagged: boolean; attachments: Array<{ filename: string | null }> };
type Calendar = { id: string; summary: string; selected: boolean; primary?: boolean };
type CalendarEvent = { id: string; calendar: string; summary: string; start: string | null; allDay: boolean };
type GitHubTraffic = { days: number; capability: { state: "available" | "permission_missing" | "authentication_required" | "unavailable"; detail: string; checkedAt: string | null }; repositories: Array<{ name: string; url: string; views: number; uniqueVisitors: number; todayViews: number }> };
type SystemSummary = { capturedAt: string; cpu: { usagePercent: number | null; cores: number; loadAverage: number[] }; memory: { totalBytes: number; availableBytes: number; usedBytes: number; usedPercent: number }; disk: { path: string; totalBytes: number; availableBytes: number; usedBytes: number; usedPercent: number } | null; thermalCelsius: number | null; network: { receivedBytesPerSecond: number | null; transmittedBytesPerSecond: number | null }; uptimeSeconds: number; system: { platform: string; release: string; architecture: string; hostname: string }; service: { name: string; status: "active" | "inactive" | "unavailable" } };
const percent = (value: number | null) => value === null ? "--" : `${Math.round(value)}%`;
const bytes = (value: number | null) => value === null ? "--" : new Intl.NumberFormat("de-DE", { notation: "compact", maximumFractionDigits: 1, style: "unit", unit: "byte", unitDisplay: "narrow" }).format(value);
const duration = (seconds: number) => `${Math.floor(seconds / 86_400)}d ${Math.floor(seconds % 86_400 / 3_600)}h`;

export function WorkOsHome() {
  const [token, setToken] = useState<string>(); const [data, setData] = useState<WorkOs>(); const [error, setError] = useState<string>();
  const [projectName, setProjectName] = useState(""); const [researchTitle, setResearchTitle] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [projectId, setProjectId] = useState(""); const [accounts, setAccounts] = useState<Array<{ id: string; email: string }>>([]); const [accountId, setAccountId] = useState(""); const [messages, setMessages] = useState<MailMessage[]>([]); const [mailFilter, setMailFilter] = useState("inbox"); const [mailSearch, setMailSearch] = useState(""); const [calendars, setCalendars] = useState<CalendarEvent[]>([]); const [events, setEvents] = useState<CalendarEvent[]>([]); const [githubTraffic, setGithubTraffic] = useState<GitHubTraffic>(); const [system, setSystem] = useState<SystemSummary>(); const [systemDetails, setSystemDetails] = useState(false);
  const headers = (json = false) => ({ "x-daily-horse-token": token ?? "", ...(json ? { "Content-Type": "application/json" } : {}) });
  const load = async (activeToken = token) => { if (!activeToken) return; const response = await fetch("/api/work-os", { headers: { "x-daily-horse-token": activeToken } }); if (!response.ok) throw new Error("Work OS konnte nicht geladen werden."); setData(await response.json() as WorkOs); };
  useEffect(() => { void (async () => { try { const response = await fetch("/api/workspace/bootstrap"); const body = await response.json() as { token?: string; error?: string }; if (!response.ok || !body.token) throw new Error(body.error ?? "Lokale Workspace-Sitzung erforderlich."); setToken(body.token); await load(body.token); } catch (reason) { setError(reason instanceof Error ? reason.message : "Work OS ist nicht verfügbar."); } })(); }, []);
  const post = async (path: string, body: object) => { const response = await fetch(path, { method: "POST", headers: headers(true), body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? "Aktion fehlgeschlagen."); await load(); };
  const patch = async (path: string, body: object) => { const response = await fetch(path, { method: "PATCH", headers: headers(true), body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? "Aktion fehlgeschlagen."); setData(await response.json() as WorkOs); };
  const submit = (action: () => Promise<void>) => void action().catch((reason) => setError(reason instanceof Error ? reason.message : "Aktion fehlgeschlagen."));
  const request = async <T,>(path: string, init?: RequestInit) => { const response = await fetch(path, { ...init, headers: { ...headers(Boolean(init?.body)), ...init?.headers } }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Anfrage fehlgeschlagen."); return body; };
  const loadMail = async (id = accountId) => { if (!id) return; const query = new URLSearchParams({ accountId: id, filter: mailFilter, ...(mailFilter === "search" ? { search: mailSearch } : {}) }); const result = await request<{ messages: MailMessage[] }>(`/api/today/mail/messages?${query}`); setMessages(result.messages); };
  const loadCalendar = async () => { const result = await request<{ calendars: Calendar[] }>("/api/today/calendars"); setCalendars(result.calendars); const today = await request<{ events: CalendarEvent[] }>("/api/today/events"); setEvents(today.events); };
  useEffect(() => { if (!token) return; void request<{ accounts: Array<{ id: string; email: string }> }>("/api/today/mail/accounts").then((result) => { setAccounts(result.accounts); setAccountId((current) => current || result.accounts[0]?.id || ""); }).catch((reason) => setError(reason.message)); void loadCalendar().catch((reason) => setError(reason.message)); void request<GitHubTraffic>("/api/github/top-repositories?days=14").then(setGithubTraffic).catch((reason) => setError(reason.message)); }, [token]);
  useEffect(() => {
    if (!token) return;
    const loadSystem = async () => { if (document.visibilityState !== "visible") return; const response = await fetch("/api/system/summary", { headers: { "x-daily-horse-token": token } }); if (!response.ok) throw new Error("Systemstatus konnte nicht geladen werden."); setSystem(await response.json() as SystemSummary); };
    void loadSystem().catch((reason) => setError(reason instanceof Error ? reason.message : "Systemstatus ist nicht verfügbar."));
    const interval = window.setInterval(() => void loadSystem().catch(() => undefined), 60_000);
    return () => window.clearInterval(interval);
  }, [token]);
  return <section className="work-os">
    <header className="today-head"><div><p>PHASE WORK OS</p><h2>Heute</h2><span>Projekte, Research und Agentenarbeit an einem ehrlichen Ort.</span></div></header>
    {error && <p className="work-os-error">{error}</p>}
    <article className="system-card" aria-label="Systemübersicht"><div className="work-card-head"><div><p>SYSTEM</p><h3>Übersicht</h3></div><span className={`system-service system-service--${system?.service.status ?? "unavailable"}`}>{system?.service.status === "active" ? "Dashboard aktiv" : system?.service.status === "inactive" ? "Dashboard inaktiv" : "Status offen"}</span></div><div className="system-glance"><div><small>CPU</small><b>{percent(system?.cpu.usagePercent ?? null)}</b></div><div><small>Speicher</small><b>{percent(system?.memory.usedPercent ?? null)}</b></div><div><small>Home</small><b>{percent(system?.disk?.usedPercent ?? null)}</b></div><div><small>Netz</small><b>{bytes(system?.network.receivedBytesPerSecond ?? null)}/s</b></div></div><button className="system-details" onClick={() => setSystemDetails(true)}>Details anzeigen</button></article>
    {systemDetails && <dialog className="system-dialog" open aria-modal="true" aria-labelledby="system-details-title" onCancel={(event) => { event.preventDefault(); setSystemDetails(false); }}><div className="system-dialog-head"><div><p>SYSTEM</p><h2 id="system-details-title">Systemdetails</h2></div><button aria-label="Systemdetails schließen" onClick={() => setSystemDetails(false)}>Schließen</button></div>{system ? <div className="system-details-grid"><p><small>Host</small><b>{system.system.hostname}</b><span>{system.system.platform} {system.system.release} · {system.system.architecture}</span></p><p><small>CPU</small><b>{percent(system.cpu.usagePercent)}</b><span>{system.cpu.cores} Kerne · Load {system.cpu.loadAverage[0]?.toFixed(2) ?? "--"}</span></p><p><small>Speicher</small><b>{bytes(system.memory.usedBytes)} / {bytes(system.memory.totalBytes)}</b><span>{bytes(system.memory.availableBytes)} verfügbar</span></p><p><small>Home-Speicher</small><b>{system.disk ? `${bytes(system.disk.usedBytes)} / ${bytes(system.disk.totalBytes)}` : "--"}</b><span>{system.disk ? `${system.disk.path} · ${bytes(system.disk.availableBytes)} frei` : "Nicht verfügbar"}</span></p><p><small>Netzwerk</small><b>↓ {bytes(system.network.receivedBytesPerSecond)}/s · ↑ {bytes(system.network.transmittedBytesPerSecond)}/s</b><span>Loopback ausgenommen</span></p><p><small>Laufzeit</small><b>{duration(system.uptimeSeconds)}</b><span>{system.thermalCelsius === null ? "Temperatur nicht verfügbar" : `${system.thermalCelsius.toFixed(1)} °C`}</span></p><p><small>Dienst</small><b>{system.service.status}</b><span>{system.service.name}</span></p></div> : <p className="empty">Systemstatus wird geladen.</p>}</dialog>}
    <section className="work-os-grid">
      <article className="work-card projects"><div className="work-card-head"><h3>Projekte</h3><span>{data?.projects.length ?? 0}</span></div><form onSubmit={(event) => { event.preventDefault(); if (projectName.trim()) submit(async () => { await post("/api/work-os/projects", { name: projectName }); setProjectName(""); }); }}><input value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="Neues Projekt"/><button>Hinzufügen</button></form>{data?.projects.length ? data.projects.map((project) => <div className="project-row" key={project.id}><div><b>{project.name}</b><small>{project.open_task_count ?? 0} offen · {project.task_count} Aufgaben</small></div><span>{project.status}</span></div>) : <p className="empty">Noch keine Projekte. Lege eines für zusammenhängende Agentenarbeit an.</p>}</article>
      <article className="work-card attention"><div className="work-card-head"><h3>Attention Center</h3><span>{data?.attention.length ?? 0}</span></div>{data?.attention.length ? data.attention.slice(0, 6).map((item) => <div className="attention-row" key={`${item.type}-${item.id}`}><b>{item.type === "setup" ? `${item.label}: Einrichtung` : item.label}</b><small>{item.detail ?? item.status}</small></div>) : <p className="empty">Keine offenen Aufmerksamkeitspunkte.</p>}</article>
      <article className="work-card queue"><div className="work-card-head"><h3>Research Queue</h3><span>{data?.research.length ?? 0}</span></div><form onSubmit={(event) => { event.preventDefault(); if (researchTitle.trim()) submit(async () => { await post("/api/work-os/research", { title: researchTitle, projectId: projectId || undefined }); setResearchTitle(""); }); }}><input value={researchTitle} onChange={(event) => setResearchTitle(event.target.value)} placeholder="Thema oder Link zum prüfen"/><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Ohne Projekt</option>{data?.projects.filter((project) => project.status === "active").map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><button>Merken</button></form>{data?.research.slice(0, 5).map((item) => <div className="research-row" key={item.id}><div><b>{item.title}</b><small>{item.project_name ?? "Unsortiert"} · {item.status}</small></div><button onClick={() => submit(() => patch(`/api/work-os/research/${item.id}`, { status: item.status === "inbox" ? "researching" : "ready" }))}>{item.status === "inbox" ? "Start" : "Fertig"}</button></div>)}</article>
      <article className="work-card tasks"><div className="work-card-head"><h3>Agentenarbeit</h3><span>{data?.tasks.length ?? 0}</span></div><form onSubmit={(event) => { event.preventDefault(); if (taskTitle.trim()) submit(async () => { await post("/api/workspace/tasks", { title: taskTitle, prompt: taskTitle, projectId: projectId || undefined }); setTaskTitle(""); }); }}><input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="Aufgabe an OpenCode"/><button>Einreihen</button></form>{data?.tasks.slice(0, 6).map((task) => <div className="task-row" key={task.id}><b>{task.title}</b><small>{data.projects.find((project) => project.id === task.project_id)?.name ?? "Ohne Projekt"} · {task.status}</small></div>)}</article>
    </section>
    <section className="setup-strip"><b>Einrichtung</b>{data?.setups.map((setup) => <span key={setup.provider}>{setup.provider === "mail" ? "Mail" : "Kalender"}: {setup.state === "setup_needed" ? "nicht verbunden" : setup.state}</span>)}<small>Keine Mail- oder Kalenderdaten werden simuliert.</small></section>
    <section className="work-os-grid integrations">
       {token && <DeviceBridge token={token} onError={setError}/>}
       <article className="work-card"><div className="work-card-head"><h3>IONOS Mail</h3><span>nur lesen</span></div>{accounts.length ? <><div className="integration-controls"><select value={accountId} onChange={(event) => { setAccountId(event.target.value); setMessages([]); }} >{accounts.map((account) => <option key={account.id} value={account.id}>{account.email}</option>)}</select><select value={mailFilter} onChange={(event) => setMailFilter(event.target.value)}><option value="inbox">Posteingang</option><option value="unread">Ungelesen</option><option value="flagged">Markiert</option><option value="search">Suche</option></select>{mailFilter === "search" && <input value={mailSearch} onChange={(event) => setMailSearch(event.target.value)} placeholder="Betreff oder Absender"/>}<button onClick={() => submit(() => loadMail())}>Laden</button></div>{messages.map((message) => <div className="attention-row" key={message.uid}><div><b>{message.unread ? "● " : ""}{message.subject}</b><small>{message.from.join(", ") || "Unbekannt"}{message.attachments.length ? ` · ${message.attachments.length} Anhang` : ""}</small></div></div>)}</> : <p className="empty">IONOS_IMAP_ACCOUNTS ist noch nicht lokal konfiguriert.</p>}</article>
       <article className="work-card"><div className="work-card-head"><h3>Google Kalender</h3><a href="/api/oauth/google/start">Google verbinden</a></div>{calendars.length ? <><div className="calendar-list">{calendars.map((calendar) => <label key={calendar.id}><input type="checkbox" checked={calendar.selected} onChange={(event) => submit(async () => { const ids = calendars.filter((item) => item.id !== calendar.id ? item.selected : event.target.checked).map((item) => item.id); await request("/api/today/calendars/selection", { method: "PUT", body: JSON.stringify({ ids }) }); await loadCalendar(); })}/>{calendar.summary}</label>)}</div>{events.map((event) => <div className="attention-row" key={`${event.calendar}-${event.id}`}><b>{event.summary}</b><small>{event.calendar} · {event.allDay ? "Ganztägig" : new Date(event.start ?? "").toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" })}</small></div>)}</> : <p className="empty">Google verbinden und Calendar API aktivieren. Der Zugriff bleibt auf Lesen beschränkt.</p>}</article>
       <article className="work-card github-today"><div className="work-card-head"><div><h3>Top Repositories</h3><small>Traffic Views · 14 Tage</small></div><span>Heute</span></div>{githubTraffic?.capability.state === "available" ? githubTraffic.repositories.length ? githubTraffic.repositories.slice(0, 4).map((repo) => <a className="github-traffic-row" key={repo.url} href={repo.url} target="_blank" rel="noreferrer"><b>{repo.name}</b><span>{repo.todayViews} heute · {repo.views} Views</span></a>) : <p className="empty">Noch keine Traffic-Views-Snapshots vorhanden.</p> : <p className="empty">{githubTraffic?.capability.detail ?? "GitHub Traffic Views wird geprüft."}</p>}</article>
     </section>
  </section>;
}
