import { useEffect, useState } from "react";
import "./today-integrations.css";

type Project = { id: string; name: string; description: string | null; status: string; task_count: number; open_task_count: number };
type Task = { id: string; title: string; status: string; priority: number; project_id: string | null };
type Research = { id: string; title: string; notes: string | null; url: string | null; status: string; project_id: string | null; project_name: string | null };
type Attention = { type: "task" | "event" | "setup"; id: string; label: string; status: string; detail: string | null };
type WorkOs = { projects: Project[]; tasks: Task[]; research: Research[]; attention: Attention[]; setups: Array<{ provider: string; state: string; detail: string }> };
type MailMessage = { uid: number; subject: string; from: string[]; date: string | null; unread: boolean; flagged: boolean; attachments: Array<{ filename: string | null }> };
type Calendar = { id: string; summary: string; selected: boolean; primary?: boolean };
type CalendarEvent = { id: string; calendar: string; summary: string; start: string | null; allDay: boolean };

export function WorkOsHome({ onOpenAgent }: { onOpenAgent: () => void }) {
  const [token, setToken] = useState<string>(); const [data, setData] = useState<WorkOs>(); const [error, setError] = useState<string>();
  const [projectName, setProjectName] = useState(""); const [researchTitle, setResearchTitle] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [projectId, setProjectId] = useState(""); const [accounts, setAccounts] = useState<Array<{ id: string; email: string }>>([]); const [accountId, setAccountId] = useState(""); const [messages, setMessages] = useState<MailMessage[]>([]); const [mailFilter, setMailFilter] = useState("inbox"); const [mailSearch, setMailSearch] = useState(""); const [calendars, setCalendars] = useState<Calendar[]>([]); const [events, setEvents] = useState<CalendarEvent[]>([]);
  const headers = (json = false) => ({ "x-daily-horse-token": token ?? "", ...(json ? { "Content-Type": "application/json" } : {}) });
  const load = async (activeToken = token) => { if (!activeToken) return; const response = await fetch("/api/work-os", { headers: { "x-daily-horse-token": activeToken } }); if (!response.ok) throw new Error("Work OS konnte nicht geladen werden."); setData(await response.json() as WorkOs); };
  useEffect(() => { void (async () => { try { const response = await fetch("/api/workspace/bootstrap"); const body = await response.json() as { token?: string; error?: string }; if (!response.ok || !body.token) throw new Error(body.error ?? "Lokale Workspace-Sitzung erforderlich."); setToken(body.token); await load(body.token); } catch (reason) { setError(reason instanceof Error ? reason.message : "Work OS ist nicht verfügbar."); } })(); }, []);
  const post = async (path: string, body: object) => { const response = await fetch(path, { method: "POST", headers: headers(true), body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? "Aktion fehlgeschlagen."); await load(); };
  const patch = async (path: string, body: object) => { const response = await fetch(path, { method: "PATCH", headers: headers(true), body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error ?? "Aktion fehlgeschlagen."); setData(await response.json() as WorkOs); };
  const submit = (action: () => Promise<void>) => void action().catch((reason) => setError(reason instanceof Error ? reason.message : "Aktion fehlgeschlagen."));
  const request = async <T,>(path: string, init?: RequestInit) => { const response = await fetch(path, { ...init, headers: { ...headers(Boolean(init?.body)), ...init?.headers } }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Anfrage fehlgeschlagen."); return body; };
  const loadMail = async (id = accountId) => { if (!id) return; const query = new URLSearchParams({ accountId: id, filter: mailFilter, ...(mailFilter === "search" ? { search: mailSearch } : {}) }); const result = await request<{ messages: MailMessage[] }>(`/api/today/mail/messages?${query}`); setMessages(result.messages); };
  const loadCalendar = async () => { const result = await request<{ calendars: Calendar[] }>("/api/today/calendars"); setCalendars(result.calendars); const today = await request<{ events: CalendarEvent[] }>("/api/today/events"); setEvents(today.events); };
  useEffect(() => { if (!token) return; void request<{ accounts: Array<{ id: string; email: string }> }>("/api/today/mail/accounts").then((result) => { setAccounts(result.accounts); setAccountId((current) => current || result.accounts[0]?.id || ""); }).catch((reason) => setError(reason.message)); void loadCalendar().catch((reason) => setError(reason.message)); }, [token]);
  return <section className="work-os">
    <header className="today-head"><div><p>PHASE WORK OS</p><h2>Heute</h2><span>Projekte, Research und Agentenarbeit an einem ehrlichen Ort.</span></div><button onClick={onOpenAgent}>OpenCode öffnen</button></header>
    {error && <p className="work-os-error">{error}</p>}
    <section className="work-os-grid">
      <article className="work-card projects"><div className="work-card-head"><h3>Projekte</h3><span>{data?.projects.length ?? 0}</span></div><form onSubmit={(event) => { event.preventDefault(); if (projectName.trim()) submit(async () => { await post("/api/work-os/projects", { name: projectName }); setProjectName(""); }); }}><input value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="Neues Projekt"/><button>Hinzufügen</button></form>{data?.projects.length ? data.projects.map((project) => <div className="project-row" key={project.id}><div><b>{project.name}</b><small>{project.open_task_count ?? 0} offen · {project.task_count} Aufgaben</small></div><span>{project.status}</span></div>) : <p className="empty">Noch keine Projekte. Lege eines für zusammenhängende Agentenarbeit an.</p>}</article>
      <article className="work-card attention"><div className="work-card-head"><h3>Attention Center</h3><span>{data?.attention.length ?? 0}</span></div>{data?.attention.length ? data.attention.slice(0, 6).map((item) => <div className="attention-row" key={`${item.type}-${item.id}`}><b>{item.type === "setup" ? `${item.label}: Einrichtung` : item.label}</b><small>{item.detail ?? item.status}</small></div>) : <p className="empty">Keine offenen Aufmerksamkeitspunkte.</p>}</article>
      <article className="work-card queue"><div className="work-card-head"><h3>Research Queue</h3><span>{data?.research.length ?? 0}</span></div><form onSubmit={(event) => { event.preventDefault(); if (researchTitle.trim()) submit(async () => { await post("/api/work-os/research", { title: researchTitle, projectId: projectId || undefined }); setResearchTitle(""); }); }}><input value={researchTitle} onChange={(event) => setResearchTitle(event.target.value)} placeholder="Thema oder Link zum prüfen"/><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Ohne Projekt</option>{data?.projects.filter((project) => project.status === "active").map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><button>Merken</button></form>{data?.research.slice(0, 5).map((item) => <div className="research-row" key={item.id}><div><b>{item.title}</b><small>{item.project_name ?? "Unsortiert"} · {item.status}</small></div><button onClick={() => submit(() => patch(`/api/work-os/research/${item.id}`, { status: item.status === "inbox" ? "researching" : "ready" }))}>{item.status === "inbox" ? "Start" : "Fertig"}</button></div>)}</article>
      <article className="work-card tasks"><div className="work-card-head"><h3>Agentenarbeit</h3><span>{data?.tasks.length ?? 0}</span></div><form onSubmit={(event) => { event.preventDefault(); if (taskTitle.trim()) submit(async () => { await post("/api/workspace/tasks", { title: taskTitle, prompt: taskTitle, projectId: projectId || undefined }); setTaskTitle(""); }); }}><input value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder="Aufgabe an OpenCode"/><button>Einreihen</button></form>{data?.tasks.slice(0, 6).map((task) => <div className="task-row" key={task.id}><b>{task.title}</b><small>{data.projects.find((project) => project.id === task.project_id)?.name ?? "Ohne Projekt"} · {task.status}</small></div>)}</article>
    </section>
    <section className="setup-strip"><b>Einrichtung</b>{data?.setups.map((setup) => <span key={setup.provider}>{setup.provider === "mail" ? "Mail" : "Kalender"}: {setup.state === "setup_needed" ? "nicht verbunden" : setup.state}</span>)}<small>Keine Mail- oder Kalenderdaten werden simuliert.</small></section>
    <section className="work-os-grid integrations">
      <article className="work-card"><div className="work-card-head"><h3>IONOS Mail</h3><span>nur lesen</span></div>{accounts.length ? <><div className="integration-controls"><select value={accountId} onChange={(event) => { setAccountId(event.target.value); setMessages([]); }} >{accounts.map((account) => <option key={account.id} value={account.id}>{account.email}</option>)}</select><select value={mailFilter} onChange={(event) => setMailFilter(event.target.value)}><option value="inbox">Posteingang</option><option value="unread">Ungelesen</option><option value="flagged">Markiert</option><option value="search">Suche</option></select>{mailFilter === "search" && <input value={mailSearch} onChange={(event) => setMailSearch(event.target.value)} placeholder="Betreff oder Absender"/>}<button onClick={() => submit(() => loadMail())}>Laden</button></div>{messages.map((message) => <div className="attention-row" key={message.uid}><div><b>{message.unread ? "● " : ""}{message.subject}</b><small>{message.from.join(", ") || "Unbekannt"}{message.attachments.length ? ` · ${message.attachments.length} Anhang` : ""}</small></div></div>)}</> : <p className="empty">IONOS_IMAP_ACCOUNTS ist noch nicht lokal konfiguriert.</p>}</article>
      <article className="work-card"><div className="work-card-head"><h3>Google Kalender</h3><a href="/api/oauth/google/start">Google verbinden</a></div>{calendars.length ? <><div className="calendar-list">{calendars.map((calendar) => <label key={calendar.id}><input type="checkbox" checked={calendar.selected} onChange={(event) => submit(async () => { const ids = calendars.filter((item) => item.id !== calendar.id ? item.selected : event.target.checked).map((item) => item.id); await request("/api/today/calendars/selection", { method: "PUT", body: JSON.stringify({ ids }) }); await loadCalendar(); })}/>{calendar.summary}</label>)}</div>{events.map((event) => <div className="attention-row" key={`${event.calendar}-${event.id}`}><b>{event.summary}</b><small>{event.calendar} · {event.allDay ? "Ganztägig" : new Date(event.start ?? "").toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" })}</small></div>)}</> : <p className="empty">Google verbinden und Calendar API aktivieren. Der Zugriff bleibt auf Lesen beschränkt.</p>}</article>
    </section>
  </section>;
}
